-- DB_GOODBUY

CREATE DATABASE DB_GOODBUY;
USE DB_GOODBUY;

CREATE TABLE TBL_USER(
	U_NO					INT AUTO_INCREMENT,
	U_ID					VARCHAR(20) UNIQUE,
	U_PW					VARCHAR(100) NOT NULL,
	U_PROFILE_THUM			VARCHAR(50),
	U_NICK					VARCHAR(20) UNIQUE,
	U_PHONE					VARCHAR(20) NOT NULL,
	U_SEX					VARCHAR(2) NOT NULL,				-- M(남) W(여)
	U_AGE					VARCHAR(10) NOT NULL,				-- 연령대
	U_POST_ADDRESS			VARCHAR(100) NOT NULL,				-- 우편번호 주소
	U_DETAIL_ADDRESS		VARCHAR(50),						-- 상세 주소
	U_SNS_ID				VARCHAR(30),						-- 구글, 네이버 ID
	U_ACTIVE				TINYINT DEFAULT 2,					-- 1(삭제된 계정), 2(활동중인 계정), 3(정지된 계정)
	U_CLASS					TINYINT DEFAULT 2,					-- 1(STOP), 2(IRON), 3(BRONZE), 4(SILVER), 5(GOLD), 6(PLATINUM), 7(DIAMOND)
	U_POINT					SMALLINT DEFAULT 100,				-- 100점 획득시 등급 상승
	U_PENALTY				TINYINT DEFAULT 0,					-- 잔여 페널티(3패널티에 1일 정지)
    U_BAN_START_DATE 		DATETIME, 							-- 정지 시작 날짜
    U_BAN_END_DATE 			DATETIME,   						-- 정지 종료 날짜
	U_REG_DATE				DATETIME DEFAULT NOW(),
	U_MOD_DATE				DATETIME DEFAULT NOW(),
	PRIMARY KEY(U_NO)
);

SELECT * FROM TBL_USER;
DROP TABLE TBL_USER;

CREATE TABLE TBL_ADMIN(
	A_NO					INT AUTO_INCREMENT,
	A_ID					VARCHAR(20) UNIQUE,
	A_PW					VARCHAR(100) NOT NULL,
	A_MAIL					VARCHAR(20) NOT NULL,
	A_PHONE					VARCHAR(20) NOT NULL,
    U_PROFILE_THUM			VARCHAR(50),
	A_ROLE					VARCHAR(10) DEFAULT 'PRE_ADMIN',		-- 1(PRE_ADMIN), 2(ADMIN)
	A_REG_DATE 				DATETIME DEFAULT NOW(),
	A_MOD_DATE 				DATETIME DEFAULT NOW(),
	PRIMARY KEY(A_NO)
);

SELECT * FROM TBL_ADMIN;

CREATE TABLE TBL_PRODUCT(
	P_NO					INT AUTO_INCREMENT,
	P_OWNER_ID				VARCHAR(20) NOT NULL,
	P_OWNER_NICK			VARCHAR(20) NOT NULL,
    P_CATEGORY				VARCHAR(20) NOT NULL,
    P_IMAGE					VARCHAR(50) NOT NULL,
	P_NAME					VARCHAR(100) NOT NULL,
	P_DESC					TEXT NOT NULL,
	P_PRICE					INT NOT NULL,
	P_STATE					TINYINT DEFAULT 3,						-- 1(취소) 2(판매완료), 3(판매중), 4(경매중)
	P_REG_DATE				DATETIME DEFAULT NOW(),
	P_MOD_DATE				DATETIME DEFAULT NOW(),
	PRIMARY KEY(P_NO)
);

SELECT * FROM TBL_PRODUCT;

CREATE TABLE TBL_SALE(
	S_NO					INT AUTO_INCREMENT,
	S_PRODUCT_NO			INT NOT NULL,
	S_SELLER_ID				VARCHAR(20) NOT NULL,
	S_SELLER_NICK			VARCHAR(20) NOT NULL,
	S_BUYER_ID				VARCHAR(20) NOT NULL,
	S_BUYER_NICK			VARCHAR(20) NOT NULL,
	S_TRADE_DATE			DATETIME,
	S_STATE					TINYINT,							-- 1(CANCEL), 2(COMPLETE)
	S_REG_DATE				DATETIME DEFAULT NOW(),
	S_MOD_DATE				DATETIME DEFAULT NOW(),
	PRIMARY KEY(S_NO)
);

SELECT * FROM TBL_SALE;

CREATE TABLE TBL_AUCTION(
	AU_NO					INT AUTO_INCREMENT,
	AU_PRODUCT_NO			INT NOT NULL,
	AU_SELLER_ID			VARCHAR(20) NOT NULL,
	AU_SELLER_NICK			VARCHAR(20) NOT NULL,
	AU_BUYER_ID				VARCHAR(20) NOT NULL,
	AU_BUYER_NICK			VARCHAR(20),
	AU_PRICE				INT,
	AU_TRADE_DATE			DATETIME,
	AU_STATE				TINYINT,							-- 1(CANCEL), 2(COMPLETE), 4(경매중)
	AU_REG_DATE				DATETIME DEFAULT NOW(),
	AU_MOD_DATE				DATETIME DEFAULT NOW(),
	PRIMARY KEY(AU_NO)
);

SELECT * FROM TBL_AUCTION;

CREATE TABLE TBL_CHAT(
	CH_NO					INT AUTO_INCREMENT,
	CH_OWNER_ID				VARCHAR(20) NOT NULL,
	CH_OWNER_NICK			VARCHAR(20) NOT NULL,
	CH_OTHER_ID				VARCHAR(20) NOT NULL,
	CH_OTHER_NICK			VARCHAR(20) NOT NULL,
	CH_BODY					TEXT,
	CH_ACTIVE				TINYINT	DEFAULT 2,					-- 1(DELETE), 2(ACTIVE)
	CH_REG_DATE 			DATETIME DEFAULT NOW(),
	CH_MOD_DATE 			DATETIME DEFAULT NOW(),
	PRIMARY KEY(CH_NO)
);

SELECT * FROM TBL_CHAT;

CREATE TABLE TBL_CHAT_IMAGE(
	CI_NO					INT AUTO_INCREMENT,
	CI_CH_NO				INT	NOT NULL,
	CI_FILE					VARCHAR(100) NOT NULL,
	PRIMARY KEY(CI_NO)
);

SELECT * FROM TBL_CHAT_IMAGE;
DROP TABLE TBL_CHAT_IMAGE;

CREATE TABLE TBL_PRODUCT_IMAGE(
	PI_NO					INT AUTO_INCREMENT,
	PI_CH_NO				INT	NOT NULL,
	PI_FILE					VARCHAR(100) NOT NULL,
	PRIMARY KEY(PI_NO)
);

SELECT * FROM TBL_CHAT_IMAGE;

CREATE TABLE TBL_CATEGORY(
	C_NO					INT AUTO_INCREMENT,
	C_NAME					VARCHAR(20),
	PRIMARY KEY(C_NO)
);

SELECT * FROM TBL_CATEGORY;


CREATE TABLE TBL_ACTIVE(
	AC_NO					INT AUTO_INCREMENT,
	AC_NAME					VARCHAR(20),						-- 1(DELETE), 2(ACTIVE), 3(STOP)
	PRIMARY KEY(AC_NO)
);

INSERT INTO TBL_ACTIVE(AC_NAME) VALUES('DELETE');
INSERT INTO TBL_ACTIVE(AC_NAME) VALUES('ACTIVE');
INSERT INTO TBL_ACTIVE(AC_NAME) VALUES('STOP');

SELECT * FROM TBL_ACTIVE;



CREATE TABLE TBL_CLASS(
	CL_NO					INT AUTO_INCREMENT,
	CL_NAME					VARCHAR(20),						-- 1(STOP), 2(IRON), 3(BRONZE), 4(SILVER), 5(GOLD), 6(PLATINUM), 7(DIAMOND)
	PRIMARY KEY(CL_NO)
);

SELECT * FROM TBL_CLASS;

CREATE TABLE TBL_STATE(
	ST_NO					INT AUTO_INCREMENT,
	ST_NAME					VARCHAR(20),						-- 1(취소) 2(판매완료), 3(판매중), 4(경매중)
	PRIMARY KEY(ST_NO)
);

SELECT * FROM TBL_STATE;

CREATE TABLE TBL_WISHLIST(
    W_NO INT AUTO_INCREMENT,
    W_USER_NO INT NOT NULL,  									-- 사용자 ID (TBL_USER의 U_NO와 연관)
    W_PRODUCT_NO INT NOT NULL,  								-- 상품 ID (TBL_PRODUCT의 P_NO와 연관)
    W_REG_DATE DATETIME DEFAULT NOW(),
    W_MOD_DATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(W_NO)
);

CREATE TABLE TBL_EVENT (
    E_NO INT AUTO_INCREMENT,               						-- 이벤트 ID
    E_TITLE VARCHAR(100) NOT NULL,        						-- 이벤트 제목
    E_IMAGE VARCHAR(255) NOT NULL,         						-- 이벤트 이미지
    E_URL VARCHAR(255),											-- 이벤트 URL
    E_DESC TEXT,                           						-- 이벤트 설명 (선택적)
    E_ACTIVE TINYINT DEFAULT 2,									-- 1(DELETE), 2(ACTIVE), 3(STOP)
    E_START_DATE DATETIME,                 						-- 이벤트 시작 날짜
    E_END_DATE DATETIME,                   						-- 이벤트 종료 날짜
    E_REG_DATE DATETIME DEFAULT NOW(),     						-- 등록 날짜
    E_MOD_DATE DATETIME DEFAULT NOW(),     						-- 수정 날짜
    PRIMARY KEY (E_NO)
);

SELECT * FROM TBL_EVENT;
DROP TABLE TBL_EVENT;

INSERT INTO TBL_CATEGORY (C_NAME) VALUE('수입명품');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('패션의류');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('패션잡화');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('뷰티');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('출산/유아동');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('모바일/태블릿');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('노트북/PC');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('카메라/캠코더');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('가구/인테리어');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('리빙/생활');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('게임');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('반려동물/취미');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('도서/음반/문구');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('티켓/쿠폰');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('스포츠');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('레저/여행');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('오토바이');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('공구/산업용품');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('무료나눔');
INSERT INTO TBL_CATEGORY (C_NAME) VALUE('중고차');